### PR TITLE
Budget feature with updated userguide

### LINKED ISSUE #54: Select the specific CCA budget to view
so that I can get a quick overview of the budget of the CCA

### PR DESCRIPTION
**Pull request by ericyjw**
Cca transaction changed from a String to a List of Entry.
Able to update Cca details and specific transaction entry.
Able to export and read transaction entry from the xml file.

Change in Budget Command:
able to display specific Cca budget

Added Delete Cca Command

resolves #54 #59

### CODE REVIEW

**Comment by ericyjw** [comment]
Cleaning up the code

**Comment by ericyjw** [comment]
Completed all intended features

**Review by GilgameshTC — APPROVED** [review]

**Comment by ericyjw** [comment]
Updated the user guide and rearranged the order of the items in section 4.1

**Comment by ericyjw** [comment]
Reorder the Commands in User Guide

**Pull request merged**
